Add back containment for `microsoft.graph.site/drive` navigation property
microsoftgraph/msgraph-metadata pull request #240
Opened 2022-12-22 07:47 UTC by irvinesunday

This PR:
- Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/238
- Removes the transform that removed `ContainsTarget=true` for the `drive` navigation property in the `site` entity type. This nav. property is now a containment nav. prop.

**NB:** Adding back the containment of this nav. prop. bumps up our OpenAPI document size from **7,951** to **8,317** paths in v1.0. Is this something that we need to assess further before proceeding with the merge?

2022-12-22 12:58 UTC, baywet requested changes
the test file needs to be updated

2022-12-22 15:39 UTC, irvinesunday commented
> the test file needs to be updated

There is no side effect in the _preprocess_csdl_test_output.xml_ file with this change.

2022-12-22 15:55 UTC, baywet commented
Are you able to run ./scripts/run-metadata-validation.ps1  locally? what's the memory use of the script?

2023-01-16 17:59 UTC, baywet commented
we shouldn't implement that change as it'd cause expansion issues.

2023-01-16 17:59 UTC, closed without merging