Add restrictions annotations for `applicationTemplates` entity set
microsoftgraph/msgraph-metadata pull request #241
Opened 2022-12-22 08:41 UTC by irvinesunday

This PR:
- Fixes https://github.com/microsoftgraph/msgraph-metadata/issues/236
- Removes insertability, updatability and deletability for the `applicationTemplates` entity set.

2022-12-22 12:58 UTC, baywet requested changes
the test file needs to be updated

2023-01-23 16:14 UTC, irvinesunday commented
> the test file needs to be updated

The _preprocess_csdl_test_output.xml_ file was updated prior.

2023-01-23 17:54 UTC, baywet approved these changes

2023-01-30 15:41 UTC, baywet approved these changes

2023-01-30 17:00 UTC, peombwa approved these changes

2023-02-06 13:29 UTC, merged